### HomePage
GET http://localhost:5000

### Get Product All 
GET http://localhost:5000/products

### Show Product
GET http://localhost:5000/products/1

### Create Product
POST http://localhost:5000/products
Content-Type: application/json

{
    "name": "Milo",
    "price": 6000
}

### Update Product
PATCH http://localhost:5000/products/1
Content-Type: application/json

{
    "name": "Nutrisari",
    "price": 5000
}

### Delete Product
DELETE http://localhost:5000/products/1

### Create User
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "vong",
    "password": "1234"
}

### Create User
GET http://localhost:5000/users/cly2rs3b30000a6dmcejph3qk
Content-Type: application/json

### Create Department
POST http://localhost:5000/departments
Content-Type: application/json

{
    "name": "Information Technology"
}

### Create Department
GET http://localhost:5000/departments/cly2ruk3600007yk55fzl0mqw
Content-Type: application/json

### Create Employee
POST http://localhost:5000/employees
Content-Type: application/json

{
    "firstName": "Vichai",
    "lastName": "Vongvorakul",
    "email": "vongvorakul@gmail.com",
    "userId": "cly2rs3b30000a6dmcejph3qk",
    "departmentId": "cly2ruk3600007yk55fzl0mqw"
}

### Get Employee
GET http://localhost:5000/employees
Content-Type: application/json

### Create Leave
POST http://localhost:5000/leaves
Content-Type: application/json

{
    "docNumber": "22405001",
    "docDate": "2022-12-01 13:06:23",
    "employeeId": "cly2rxsxk0002f2lgx1ym9q2r", 
    "leaveType": "ANUAL", 
    "remarks": "This is a new employee",
    "leaveLines": [
        {"startDate": "2022-12-01 13:06:23", "endDate": "2022-12-01 13:06:23"},
        {"startDate": "2022-12-02 13:06:23", "endDate": "2022-12-02 13:06:23"},
        {"startDate": "2022-12-03 13:06:23", "endDate": "2022-12-03 13:06:23"}
    ]
}
### Upsert Leave
PATCH http://localhost:5000/leaves/cly3vdaww0000b0th0rlycrui
Content-Type: application/json

{
    "docNumber": "22405001",
    "docDate": "2022-12-01 13:06:23",
    "employeeId": "cly2rxsxk0002f2lgx1ym9q2r", 
    "leaveType": "SICK", 
    "remarks": "This is a upserted employee",
    "leaveLines": [
        {"id": "3", "startDate": "2022-12-13 13:06:23", "endDate": "2022-12-12 13:06:23"},
        {"startDate": "2022-12-02 13:06:23", "endDate": "2022-12-02 13:06:23"},
        {"startDate": "2022-12-03 13:06:23", "endDate": "2022-12-03 13:06:23"}
    ]
}

### Get Leaves
GET http://localhost:5000/leaves/cly3vdaww0000b0th0rlycrui
Content-Type: application/json

### Get Leave Lines
GET http://localhost:5000/leave-lines
Content-Type: application/json

### Get Leave Lines
PATCH http://localhost:5000/leaves/cly3vdaww0000b0th0rlycrui/set-leave-status
Content-Type: application/json

{
    "id": "cly3vdaww0000b0th0rlycrui",
    "submittedAt": "2015-06-02T13:05:45",
    "approvedAt": "2015-07-02T13:05:45",
    "rejectedAt": "2015-07-02T13:05:45"
}
